### PR TITLE
Bug fixed: domainRegistry interface invocation

### PR DESCRIPTION
**Pull request by Heriam**

### CODE REVIEW

**Comment by jboulmal** [comment]
Hi @Heriam Do you want to merge your updates to master branch ?

**Comment by Heriam** [comment]
Hi @jboulmal  I fixed the problem yesterday. It turns out that they changed the interface of domain registry, so we have to accordingly modify our code when we invoke the domain registry.

**Comment by Heriam** [comment]
If you want to test you can fisrt update your domain registry and see if your msg node reports the same error like yesterday. And then update your msg node code with my update to see if my update fix the error. Thank you!

**Comment by jboulmal** [comment]
Then we need to update also develop branch, could also send pull request for that. currently I don't have time for testing.

**Pull request merged**
